[2024-04-19 16:28:59,011] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T16:28:55.655103+00:00 [queued]>
[2024-04-19 16:28:59,021] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T16:28:55.655103+00:00 [queued]>
[2024-04-19 16:28:59,022] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:28:59,023] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 16:28:59,024] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:28:59,039] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-19 16:28:55.655103+00:00
[2024-04-19 16:28:59,044] {standard_task_runner.py:52} INFO - Started process 280 to run task
[2024-04-19 16:28:59,046] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'manual__2024-04-19T16:28:55.655103+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpui07cln5', '--error-file', '/tmp/tmpil7iw4sp']
[2024-04-19 16:28:59,048] {standard_task_runner.py:80} INFO - Job 55: Subtask notificar_objetos_cercanos
[2024-04-19 16:28:59,113] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T16:28:55.655103+00:00 [running]> on host 2e237166a7ec
[2024-04-19 16:28:59,185] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-19T16:28:55.655103+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-19T16:28:55.655103+00:00
[2024-04-19 16:28:59,251] {logging_mixin.py:115} INFO - [Errno -2] Name or service not known
[2024-04-19 16:28:59,251] {logging_mixin.py:115} INFO - Failure
[2024-04-19 16:28:59,252] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 16:28:59,264] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240419T162855, start_date=20240419T162859, end_date=20240419T162859
[2024-04-19 16:28:59,299] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 16:28:59,351] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
