[2024-04-19 16:28:07,267] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-19 16:28:07,305] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-19 16:28:07,305] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:28:07,306] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 16:28:07,307] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:28:07,325] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-16 00:00:00+00:00
[2024-04-19 16:28:07,341] {standard_task_runner.py:52} INFO - Started process 247 to run task
[2024-04-19 16:28:07,345] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'scheduled__2024-04-16T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpd6r73xrw', '--error-file', '/tmp/tmp9wuutl0r']
[2024-04-19 16:28:07,365] {standard_task_runner.py:80} INFO - Job 54: Subtask notificar_objetos_cercanos
[2024-04-19 16:28:07,738] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos scheduled__2024-04-16T00:00:00+00:00 [running]> on host 2e237166a7ec
[2024-04-19 16:28:07,978] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-16T00:00:00+00:00
[2024-04-19 16:28:10,039] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials p10-20020a170902e34a00b001e49bce99d9sm3550008plc.95 - gsmtp')
[2024-04-19 16:28:10,040] {logging_mixin.py:115} INFO - Failure
[2024-04-19 16:28:10,040] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 16:28:10,057] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240416T000000, start_date=20240419T162807, end_date=20240419T162810
[2024-04-19 16:28:10,084] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 16:28:10,129] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
