[2024-04-09 21:47:53,393] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Convertir_dataframe manual__2024-04-09T21:47:50.181506+00:00 [queued]>
[2024-04-09 21:47:53,405] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Convertir_dataframe manual__2024-04-09T21:47:50.181506+00:00 [queued]>
[2024-04-09 21:47:53,405] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:47:53,406] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-09 21:47:53,407] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:47:53,423] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): Convertir_dataframe> on 2024-04-09 21:47:50.181506+00:00
[2024-04-09 21:47:53,427] {standard_task_runner.py:52} INFO - Started process 1000 to run task
[2024-04-09 21:47:53,430] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'Convertir_dataframe', 'manual__2024-04-09T21:47:50.181506+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpgll95032', '--error-file', '/tmp/tmpx4pwq75o']
[2024-04-09 21:47:53,432] {standard_task_runner.py:80} INFO - Job 170: Subtask Convertir_dataframe
[2024-04-09 21:47:53,492] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.Convertir_dataframe manual__2024-04-09T21:47:50.181506+00:00 [running]> on host c346f321fefe
[2024-04-09 21:47:53,556] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=Convertir_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2024-04-09T21:47:50.181506+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-09T21:47:50.181506+00:00
[2024-04-09 21:47:53,558] {logging_mixin.py:115} INFO - Hola
[2024-04-09 21:47:54,454] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 94, in convertir_dataframe
    neo_json = neo.json()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'json'
[2024-04-09 21:47:54,479] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=NEO_coderhouse, task_id=Convertir_dataframe, execution_date=20240409T214750, start_date=20240409T214753, end_date=20240409T214754
[2024-04-09 21:47:54,491] {standard_task_runner.py:97} ERROR - Failed to execute job 170 for task Convertir_dataframe ('DataFrame' object has no attribute 'json'; 1000)
[2024-04-09 21:47:54,530] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-09 21:47:54,569] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
