[2024-04-19 16:28:07,267] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-04-19 16:28:07,289] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-04-19 16:28:07,289] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:28:07,290] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 16:28:07,290] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:28:07,320] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-18 00:00:00+00:00
[2024-04-19 16:28:07,333] {standard_task_runner.py:52} INFO - Started process 245 to run task
[2024-04-19 16:28:07,342] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'scheduled__2024-04-18T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmplk0m1k36', '--error-file', '/tmp/tmpq7tvlxvh']
[2024-04-19 16:28:07,360] {standard_task_runner.py:80} INFO - Job 53: Subtask notificar_objetos_cercanos
[2024-04-19 16:28:07,738] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos scheduled__2024-04-18T00:00:00+00:00 [running]> on host 2e237166a7ec
[2024-04-19 16:28:07,973] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-18T00:00:00+00:00
[2024-04-19 16:28:09,974] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials k12-20020aa7820c000000b006eaf186e078sm3404981pfi.132 - gsmtp')
[2024-04-19 16:28:09,974] {logging_mixin.py:115} INFO - Failure
[2024-04-19 16:28:09,974] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 16:28:10,007] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240418T000000, start_date=20240419T162807, end_date=20240419T162810
[2024-04-19 16:28:10,053] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 16:28:10,097] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
