[2024-04-09 16:13:55,584] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.inicio scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-09 16:13:55,599] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.inicio scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-09 16:13:55,599] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 16:13:55,600] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-04-09 16:13:55,600] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 16:13:55,619] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): inicio> on 2024-04-08 00:00:00+00:00
[2024-04-09 16:13:55,624] {standard_task_runner.py:52} INFO - Started process 475 to run task
[2024-04-09 16:13:55,627] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'inicio', 'scheduled__2024-04-08T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpflvqm1fv', '--error-file', '/tmp/tmprvwbci_b']
[2024-04-09 16:13:55,628] {standard_task_runner.py:80} INFO - Job 77: Subtask inicio
[2024-04-09 16:13:55,954] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.inicio scheduled__2024-04-08T00:00:00+00:00 [running]> on host 7da9ebceb107
[2024-04-09 16:13:56,244] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=inicio
AIRFLOW_CTX_EXECUTION_DATE=2024-04-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-08T00:00:00+00:00
[2024-04-09 16:13:56,258] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-04-09 16:13:56,262] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Realizando consulta...']
[2024-04-09 16:13:56,291] {subprocess.py:85} INFO - Output:
[2024-04-09 16:13:56,312] {subprocess.py:92} INFO - bash: line 1: Realizando: command not found
[2024-04-09 16:13:56,313] {subprocess.py:96} INFO - Command exited with return code 127
[2024-04-09 16:13:56,355] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-04-09 16:13:56,360] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=NEO_coderhouse, task_id=inicio, execution_date=20240408T000000, start_date=20240409T161355, end_date=20240409T161356
[2024-04-09 16:13:56,379] {standard_task_runner.py:97} ERROR - Failed to execute job 77 for task inicio (Bash command failed. The command returned a non-zero exit code 127.; 475)
[2024-04-09 16:13:56,403] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-09 16:13:56,458] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
