[2024-04-19 19:26:54,278] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Cargar_datos_redshift manual__2024-04-19T19:26:43.778482+00:00 [queued]>
[2024-04-19 19:26:54,291] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Cargar_datos_redshift manual__2024-04-19T19:26:43.778482+00:00 [queued]>
[2024-04-19 19:26:54,292] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 19:26:54,293] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 19:26:54,294] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 19:26:54,309] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): Cargar_datos_redshift> on 2024-04-19 19:26:43.778482+00:00
[2024-04-19 19:26:54,315] {standard_task_runner.py:52} INFO - Started process 340 to run task
[2024-04-19 19:26:54,318] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'Cargar_datos_redshift', 'manual__2024-04-19T19:26:43.778482+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpf87_2w08', '--error-file', '/tmp/tmprgbc26gc']
[2024-04-19 19:26:54,321] {standard_task_runner.py:80} INFO - Job 88: Subtask Cargar_datos_redshift
[2024-04-19 19:26:54,387] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.Cargar_datos_redshift manual__2024-04-19T19:26:43.778482+00:00 [running]> on host 2e237166a7ec
[2024-04-19 19:26:54,455] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=Cargar_datos_redshift
AIRFLOW_CTX_EXECUTION_DATE=2024-04-19T19:26:43.778482+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-19T19:26:43.778482+00:00
[2024-04-19 19:26:54,456] {logging_mixin.py:115} INFO - Hola
[2024-04-19 19:26:55,362] {logging_mixin.py:115} INFO - Cantidad de registros extraidos el 2024-04-19 - 18
[2024-04-19 19:26:55,363] {logging_mixin.py:115} INFO - Se van a insertar 18 registros.
[2024-04-19 19:27:00,090] {logging_mixin.py:115} INFO - No fue posible conectar
[2024-04-19 19:27:00,091] {logging_mixin.py:115} INFO - (psycopg2.errors.UndefinedColumn) column "sentry_data" of relation "neo" does not exist

[SQL: INSERT INTO neo (neo_reference_id, name, absolute_magnitude_h, is_potentially_hazardous_asteroid, is_sentry_object, sentry_data, estimated_diameter_min, estimated_diameter_max, close_approach_date_full, kilometers_per_second, distance_kilometers, orbiting_body) VALUES (%(neo_reference_id)s, %(name)s, %(absolute_magnitude_h)s, %(is_potentially_hazardous_asteroid)s, %(is_sentry_object)s, %(sentry_data)s, %(estimated_diameter_min)s, %(estimated_diameter_max)s, %(close_approach_date_full)s, %(kilometers_per_second)s, %(distance_kilometers)s, %(orbiting_body)s)]
[parameters: ({'neo_reference_id': 2523609, 'name': '523609 (2005 PJ2)', 'absolute_magnitude_h': 19.53, 'is_potentially_hazardous_asteroid': True, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 330.0311833581, 'estimated_diameter_max': 737.9721606833, 'close_approach_date_full': '2024-Apr-19 14:28', 'kilometers_per_second': 22.9484601531, 'distance_kilometers': 40850317.71260583, 'orbiting_body': 'Earth'}, {'neo_reference_id': 3457849, 'name': '(2009 HL21)', 'absolute_magnitude_h': 22.55, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 82.1400525962, 'estimated_diameter_max': 183.6707412805, 'close_approach_date_full': '2024-Apr-19 04:54', 'kilometers_per_second': 12.0990998055, 'distance_kilometers': 17726846.457095288, 'orbiting_body': 'Earth'}, {'neo_reference_id': 3638430, 'name': '(2013 JR22)', 'absolute_magnitude_h': 20.87, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 178.0553291829, 'estimated_diameter_max': 398.1438198091, 'close_approach_date_full': '2024-Apr-19 07:59', 'kilometers_per_second': 21.0815781233, 'distance_kilometers': 18729118.347057093, 'orbiting_body': 'Earth'}, {'neo_reference_id': 3648878, 'name': '(2013 TG6)', 'absolute_magnitude_h': 26.58, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 12.8397029582, 'estimated_diameter_max': 28.7104486255, 'close_approach_date_full': '2024-Apr-19 07:26', 'kilometers_per_second': 5.1134664778, 'distance_kilometers': 25917287.39867957, 'orbiting_body': 'Earth'}, {'neo_reference_id': 3678561, 'name': '(2014 OZ337)', 'absolute_magnitude_h': 22.5, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 84.0533402073, 'estimated_diameter_max': 187.9489824394, 'close_approach_date_full': '2024-Apr-19 03:31', 'kilometers_per_second': 18.0160902822, 'distance_kilometers': 40274263.07952999, 'orbiting_body': 'Earth'}, {'neo_reference_id': 3780786, 'name': '(2017 QY2)', 'absolute_magnitude_h': 21.24, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 150.1602479051, 'estimated_diameter_max': 335.768521834, 'close_approach_date_full': '2024-Apr-19 03:18', 'kilometers_per_second': 17.1703852244, 'distance_kilometers': 36709388.158667415, 'orbiting_body': 'Earth'}, {'neo_reference_id': 3781983, 'name': '(2017 SA20)', 'absolute_magnitude_h': 28.36, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': True, 'sentry_data': 'http://api.nasa.gov/neo/rest/v1/neo/sentry/3781983?api_key=1vQKAD9leMbOeppmESs3aFLlbjnAcoylVNyxdWdj', 'estimated_diameter_min': 5.6565935842, 'estimated_diameter_max': 12.6485277754, 'close_approach_date_full': '2024-Apr-19 09:48', 'kilometers_per_second': 6.1926913915, 'distance_kilometers': 1464210.889195511, 'orbiting_body': 'Earth'}, {'neo_reference_id': 3788901, 'name': '(2017 VE)', 'absolute_magnitude_h': 26.6, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 12.7219878539, 'estimated_diameter_max': 28.4472296503, 'close_approach_date_full': '2024-Apr-19 13:17', 'kilometers_per_second': 27.0425462795, 'distance_kilometers': 72301132.65013607, 'orbiting_body': 'Earth'}  ... displaying 10 of 18 total bound parameter sets ...  {'neo_reference_id': 54433731, 'name': '(2024 GT3)', 'absolute_magnitude_h': 24.41, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 34.8782733159, 'estimated_diameter_max': 77.9901900722, 'close_approach_date_full': '2024-Apr-19 10:11', 'kilometers_per_second': 8.1294825273, 'distance_kilometers': 11457330.922727278, 'orbiting_body': 'Earth'}, {'neo_reference_id': 54435202, 'name': '(2024 HL)', 'absolute_magnitude_h': 26.542, 'is_potentially_hazardous_asteroid': False, 'is_sentry_object': False, 'sentry_data': None, 'estimated_diameter_min': 13.0663707424, 'estimated_diameter_max': 29.2172931992, 'close_approach_date_full': '2024-Apr-19 23:53', 'kilometers_per_second': 19.6630253434, 'distance_kilometers': 1855105.426132393, 'orbiting_body': 'Earth'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-04-19 19:27:00,092] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 19:27:00,110] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=Cargar_datos_redshift, execution_date=20240419T192643, start_date=20240419T192654, end_date=20240419T192700
[2024-04-19 19:27:00,159] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 19:27:00,183] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
