[2024-04-09 21:28:17,542] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Convertir_dataframe manual__2024-04-09T21:22:10.400123+00:00 [queued]>
[2024-04-09 21:28:17,559] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Convertir_dataframe manual__2024-04-09T21:22:10.400123+00:00 [queued]>
[2024-04-09 21:28:17,560] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:28:17,561] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-09 21:28:17,561] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:28:17,585] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): Convertir_dataframe> on 2024-04-09 21:22:10.400123+00:00
[2024-04-09 21:28:17,592] {standard_task_runner.py:52} INFO - Started process 750 to run task
[2024-04-09 21:28:17,596] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'Convertir_dataframe', 'manual__2024-04-09T21:22:10.400123+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpm8floal8', '--error-file', '/tmp/tmp1le4u3fy']
[2024-04-09 21:28:17,597] {standard_task_runner.py:80} INFO - Job 109: Subtask Convertir_dataframe
[2024-04-09 21:28:17,665] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.Convertir_dataframe manual__2024-04-09T21:22:10.400123+00:00 [running]> on host c346f321fefe
[2024-04-09 21:28:17,731] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=Convertir_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2024-04-09T21:22:10.400123+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-09T21:22:10.400123+00:00
[2024-04-09 21:28:17,732] {logging_mixin.py:115} INFO - Hola
[2024-04-09 21:28:18,581] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 59, in convertir_dataframe
    respuesta = consulta_api_nasa()
  File "/opt/airflow/dags/dag.py", line 47, in consulta_api_nasa
    if respuesta.status_code == 200:
NameError: name 'respuesta' is not defined
[2024-04-09 21:28:18,592] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=NEO_coderhouse, task_id=Convertir_dataframe, execution_date=20240409T212210, start_date=20240409T212817, end_date=20240409T212818
[2024-04-09 21:28:18,603] {standard_task_runner.py:97} ERROR - Failed to execute job 109 for task Convertir_dataframe (name 'respuesta' is not defined; 750)
[2024-04-09 21:28:18,614] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-09 21:28:18,651] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
